services:
  gcs:
    url: https://storage.googleapis.com/storage/v1/b/${BUCKET_NAME}/o
    response_header_timeout_seconds: 5
    credentials:
      gcp_metadata:
        scopes:
          - "https://www.googleapis.com/auth/devstorage.read_only"
  cloudrun:
    url: ${BQ_CONNECTOR_URL}
    credentials:
      gcp_metadata:
        audience: ${BQ_CONNECTOR_URL}

decision_logs:
  service: cloudrun
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 10

bundles:
  authz:
    service: gcs
    resource: 'bundle.tar.gz?alt=media'
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
